# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure ("2") do |config|
        config.vm.define "os" do |os|
                os.vm.box = "centos/7"
                os.vm.host_name = "RPM"
                os.vm.network "private_network", ip: '192.168.11.101'
                os.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "256"]
        end
                os.vm.provision "shell", inline: <<SHELL

                src0=https://nginx.org/packages/centos/7/SRPMS/nginx-1.14.1-1.el7_4.ngx.src.rpm
                op0=/root/nginx-1.14.1-1.el7_4.ngx.src.rpm
                src2=https://www.openssl.org/source/openssl-1.1.1f.tar.gz
                op2=/root/latest.tar.gz
                op3=/root/
                src4=/root/rpmbuild/SPECS/nginx.spec
                src5=/vagrant/SPECfile
                op5=/root/rpmbuild/SPECS/nginx.spec
                src5=/root/rpmbuild/SPECS/nginx.spec
                src6=/root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
                op6=/etc/nginx/conf.d/default.conf
                src8=/root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm     
                src9="https://www.percona.com/redir/downloads/percona-release/redhat/1.0-17/percona-release-1.0-17.noarch.rpm"
                op8=/usr/share/nginx/html/repo/
                op9=/usr/share/nginx/html/repo/percona-release-0.1-6.noarch.rpm
                op10=/etc/yum.repos.d/custom.repo
        
                yum install -y redhat-lsb-core gcc wget rpmdevtools rpm-build createrepo yum-utils
                wget $src0 -O $op0
                rpm -i $op0
                wget $src2 -O $op2
                tar -xf $op2 -C $op3     
                yum-builddep $src4 -y #         cp -f $src5 $op5                
                i=$(ls -l /root/|awk '/openssl/{print $9}')
                sed -i 's/openssl-1.1.1a/'$i'/' /root/rpmbuild/SPECS/nginx.spec 
                rpmbuild -bb $src5
                yum localinstall -y $src6
                N=11; sed -e $N"s/^/autoindex on;\\n/" -i $op6
                systemctl start nginx
                nginx -s reload 
                systemctl start nginx
                mkdir $op8
                cp $src8 $op8 -f
                wget $src9 -O $op9
                createrepo $op8
                cat > $op10 << EOF
[custom]
name=custom
baseurl=http://localhost/repo
gpgcheck=0
enabled=1
EOF
                yum-config-manager --disable base >/dev/null
                echo "###test percona###"> /vagrant/result_repo.list
                yum list | grep custom >> /vagrant/result_repo.list
                echo -e "\n###test nginx###" >> /vagrant/result_repo.list
                yum provides nginx >>/vagrant/result_repo.list
SHELL
        end
end

