---
- name: "##### eth1 centralRouter --> inetRouter #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/eth1_inet1
    dest: "{{ eth_01 }}"
  notify: restart router

- name: "##### eth2 centralRouter --> inetRouter2 #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/eth2_inet2
    dest: "{{ eth_02 }}"
  notify: restart router

- name: "##### eth3 centralRouter --> cetnralServer #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/eth3_srv
    dest: "{{ eth_03 }}"
  notify: restart router

- name: "##### route 192.168.11.0/8 via 192.168.155.1 #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/route-eth2
    dest: "{{ route_eth2 }}"
  notify: restart router

- name: "##### copy knock.sh #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/knock.sh
    dest: /vagrant/knock.sh
  notify: restart router
