# -*- mode: ruby -*-
# vi: set ft=ruby:
home = ENV['HOME']

MACHINES = {
  :'pg' => {
      :box_name => "centos/7",
      :ip_addr => '192.168.100.101',
  },
  :'hot-standby' => {
      :box_name => "centos/7",
      :ip_addr => '192.168.100.102',
  },
  :'balancer' => {
      :box_name => "centos/7",
      :ip_addr => '192.168.100.103',
  },
  :'barman' => {
      :box_name => "centos/7",
      :ip_addr => '192.168.100.104',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip:boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
          vb.name = boxname.to_s
        end
          box.vm.provision "ansible" do |ansible|
#	        ansible.verbose = "vvv"
            ansible.playbook = "playbooks/pgsql.yml"
            ansible.become = "true"
          end
      end
    end
end
