#- name:
#  shell: setenforce 0

- name:
  include_vars: 
    file: ../roles/vars/all.yml

- name:
  template:
    src: ../templates/epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name:
  yum:
    name: "{{ packages }} "
    state: present
 
- name: static.key
  template:
    src: ../templates/server/etc/openvpn/static.key
    dest: /etc/openvpn/static.key

- name:
  file:
    path: /etc/openvpn/server.conf
    mode: '0600'
    state: touch
  
- name:
  blockinfile:
    path: /etc/openvpn/server.conf
    block: |
      dev tap
      remote 192.168.10.10
      ifconfig 10.10.10.2 255.255.255.0
      topology subnet
      route 192.168.10.0 255.255.255.0
      secret /etc/openvpn/static.key
      comp-lzo
      status /var/log/openvpn-status.log
      log /var/log/openvpn.log
      verb 3

- name:
  systemd:
    name: openvpn@server
    state: started
    enabled: true
