- name: main deploy for mysql homework
  hosts:
    - master
    - slave
  gather_facts: no
  become: true
  roles:
    - role: roles
  tasks:
    - include: ../roles/tasks/{{ inventory_hostname }}.yml
#  handlers:
#    - include: ../roles/handlers/all_handlers.yml
