# -*- mode: ruby -*-
# vi: set ft=ruby:
home = ENV['HOME']

MACHINES = {
  :'server' => {
      :box_name => "centos/7",
      :ip_addr => '192.168.100.101',
  },
  :'client' => {
      :box_name => "centos/7",
      :ip_addr => '192.168.100.102',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip:boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.name = boxname.to_s
          case boxname.to_s
          when "server"
            vb.customize ["modifyvm", :id, "--memory", "2560"]
            vb.customize ["modifyvm", :id, "--cpus", "4"]
          when "client"
            vb.customize ["modifyvm", :id, "--memory", "256"]

          end
        end
       box.vm.provision "ansible" do |ansible|
            	        #ansible.verbose = "vvv"
                      ansible.playbook = "playbooks/main_ipa.yml"
                      ansible.become = "true"
                    end
      end
    end
end
