- name:
  shell: setenforce 0

- name:
  include_vars: 
    file: ../roles/vars/{{ inventory_hostname }}.yml

- name:
  template:
    src: ../templates/epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name:
  yum:
    name: "{{ packages }} "
    state: present
 
- name:
  shell: |
    /usr/share/easy-rsa/3.0.7/easyrsa init-pki;
    echo 'rasvpn' | /usr/share/easy-rsa/3.0.7/easyrsa build-ca nopass;
    echo 'rasvpn' | /usr/share/easy-rsa/3.0.7/easyrsa gen-req server nopass;
    echo 'yes' | /usr/share/easy-rsa/3.0.7/easyrsa sign-req server server;
    /usr/share/easy-rsa/3.0.7/easyrsa gen-dh;
    openvpn --genkey --secret ta.key;
    echo 'client' | /usr/share/easy-rsa/3/easyrsa gen-req client nopass;
    echo 'yes' | /usr/share/easy-rsa/3/easyrsa sign-req client client
  args:
    chdir: /etc/openvpn/

- name:
  file:
    path: /etc/openvpn/server.conf
    mode: '0600'
    state: touch

- name:
  blockinfile:
    path: /etc/openvpn/server.conf
    block: |
      port 1207
      proto udp
      dev tun
      ca /etc/openvpn/pki/ca.crt
      cert /etc/openvpn/pki/issued/server.crt
      key /etc/openvpn/pki/private/server.key
      dh /etc/openvpn/pki/dh.pem
      server 10.10.10.0 255.255.255.0
      push "route 192.168.10.0 255.255.255.0"
      ifconfig-pool-persist ipp.txt
      client-to-client
      client-config-dir /etc/openvpn/client
      keepalive 10 120
      comp-lzo
      persist-key
      persist-tun
      status /var/log/openvpn-status.log
      log /var/log/openvpn.log
      verb 3

- name:
  shell: echo 'iroute 192.168.33.0 255.255.255.0' > /etc/openvpn/client/client

- name:
  systemd:
    name: openvpn@server
    state: started
    enabled: true

- name:
  file:
    path: /vagrant/parent
    state: directory

- name: Moving file.
  shell: |
    cp /etc/openvpn/pki/ca.crt /vagrant/parent
    cp /etc/openvpn/pki/issued/client.crt /vagrant/parent
    cp /etc/openvpn/pki/private/client.key /vagrant/parent


- name: Get file from remote
  synchronize:
    src: /vagrant/parent/
    dest: ../roles/templates/pki
    mode: pull