- name: "Create user: git"
  user:
    name: git
    state: present
    uid: 995
    home: /var/opt/gitlab
    createhome: yes
    shell: /bin/sh

- name: "Configure NFS share: start firewall services"
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: "Configure NFS share: Configuring firewall services"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - nfs
    - mountd
    - rpc-bind

- name: "Configure NFS share: Configuring firewall services"
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 50370/udp
    - 52169/udp
    - 20048/udp
    - 2049/udp
    - 42494/udp
    - 41310/udp

- name: "Configure NFS share: add line in /etc/fstab"
  blockinfile:
    path: /etc/fstab
    block: |
      192.168.100.230:/mnt    /var/opt/gitlab/git-data   nfs    rsize=8192,wsize=8192,timeo=14,intr,udp,nfsvers=3

- name: "Configure NFS share: create dir"
  file:
    path: /var/opt/gitlab/git-data
    state: directory

- name: "Configure NFS share: mount"
  shell: |
    mount -a

#- name: Rules for firewalld
#  shell: |
#    firewall-cmd \
#    --add-port=50370/udp \
#    --add-port=52169/udp \
#    --add-port=20048/udp \
#    --add-port=2049/udp \
#    --add-port=42494/udp \
#    --add-port=41310/udp \
#    --permanent
#    firewall-cmd --permanent --add-service=nfs
#    firewall-cmd --permanent --add-service=mountd
#    firewall-cmd --permanent --add-service=rpc-bind
#    firewall-cmd --reload
#- name: Mount
#  shell: |
#    echo "192.168.100.105:/obmen    /var/opt/gitlab/git-data   nfs    rsize=8192,wsize=8192,timeo=14,intr,udp,nfsvers=3" >> /etc/fstab
#    mount -a

#- name: Create /obmen_1
#  file:
#    path: /obmen_1
#    state: directory
#    mode: "0777"
