- name: Install repo
  shell: |
    rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    yum install centos-release-scl -y
    sed -i 's!enabled=0!enabled=1!' /etc/yum.repos.d/zabbix.repo
    yum clean all

- name: Install php, zabbix, postgres
  shell: |
    yum install epel-release -y
    yum install setools setroubleshoot-server -y
    yum install nginx -y
    yum install zabbix-server-pgsql zabbix-agent -y
    yum install zabbix-web-pgsql-scl -y
    yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm -y
    yum install postgresql11-server -y

- name: Preup PostgreSQL
  shell: |
    /usr/pgsql-11/bin/postgresql-11-setup initdb
    sed -i 's!host    all             all             ::1/128                 ident!host    all             all             ::1/128                 trust!' /var/lib/pgsql/11/data/pg_hba.conf
    sed -i 's!host    all             all             127.0.0.1/32            ident!host    all             all             127.0.0.1/32            trust!' /var/lib/pgsql/11/data/pg_hba.conf
    sed -i 's!local   all             all                                     peer!local   all             all                                     trust!' /var/lib/pgsql/11/data/pg_hba.conf

- name: Preup Zabbix
  shell: |
    sed -i 's/\#\ DBPassword=/DBPassword=12345678/' /etc/zabbix/zabbix_server.conf
    sed -i 's!listen.acl_users = apache!listen.acl_users = apache,nginx!'  /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
    sed -i  's!; php_value\[date.timezone]!php_value\[date.timezone]!' /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
    sed -i 's!# DBPort=!DBPort=5432!' /etc/zabbix/zabbix_server.conf

- name: Create site_zabbix.conf
  shell: |
    cat<<EOF>/etc/nginx/conf.d/zabbix.conf
    server {
    listen          83;
    server_name     zabbix.com;

            root    /usr/share/zabbix;

            index   index.php;

            location = /favicon.ico {
                    log_not_found   off;
            }

            location / {
                    try_files       \$uri \$uri/ =404;
            }

            location /assets {
                    access_log      off;
                    expires         10d;
            }

            location ~ /\.ht {
                    deny            all;
            }

            location ~ /(api\/|conf[^\.]|include|locale) {
                    deny            all;
                    return          404;
            }

            location ~ [^/]\.php(/|\$) {
                    fastcgi_pass    unix:/var/opt/rh/rh-php72/run/php-fpm/zabbix.sock;
                    fastcgi_split_path_info ^(.+\.php)(/.+)\$;
                    fastcgi_index   index.php;

                    fastcgi_param   DOCUMENT_ROOT   /usr/share/zabbix;
                    fastcgi_param   SCRIPT_FILENAME /usr/share/zabbix\$fastcgi_script_name;
                    fastcgi_param   PATH_TRANSLATED /usr/share/zabbix\$fastcgi_script_name;

                    include fastcgi_params;
                    fastcgi_param   QUERY_STRING    \$query_string;
                    fastcgi_param   REQUEST_METHOD  \$request_method;
                    fastcgi_param   CONTENT_TYPE    \$content_type;
                    fastcgi_param   CONTENT_LENGTH  \$content_length;

                    fastcgi_intercept_errors        on;
                    fastcgi_ignore_client_abort     off;
                    fastcgi_connect_timeout         60;
                    fastcgi_send_timeout            180;
                    fastcgi_read_timeout            180;
                    fastcgi_buffer_size             128k;
                    fastcgi_buffers                 4 256k;
                    fastcgi_busy_buffers_size       256k;
                    fastcgi_temp_file_write_size    256k;
            }
    }
    EOF

- name: Prestart nginx for SELinux
  shell: |
    systemctl restart nginx
  ignore_errors: True

- name: Configure SELinux
  shell: |
    sudo setsebool -P httpd_can_network_connect 1
    ausearch -c 'nginx' --raw | audit2allow -M my-nginx
    semodule -i my-nginx.pp
    rm -f ./my-nginx.pp; > /var/log/audit/audit.log
  ignore_errors: True

- name: Start service
  shell: |
    systemctl start zabbix-server zabbix-agent rh-php72-php-fpm.service  postgresql-11.service
    systemctl enable nginx; systemctl restart nginx
