- name:
  include_vars:
    file: "{{ item }}"
  loop:
    - ../roles/vars/packages.yml
    - ../roles/vars/sysctl_name.yml
    - ../roles/vars/route_files.yml

- name: install packages
  yum:
    name: "{{ central_packages }}"
    state: present

- name: Set ipv4.proxy - true
  sysctl:
    name: "{{ item.n }}"
    value: "{{ item.v }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items: "{{ sysctl_name }}"

- name: start NetworkManager-dispatcher
  systemd:
    name: NetworkManager-dispatcher.service
    state: started
    enabled: true

- name: Create VID5 for testServer1
  shell: nmcli con add type vlan con-name eth1.5 ifname eth1.5 dev eth1 id 5 ip4 10.10.10.5/24

- name: Create VID5 for testClient1
  shell: nmcli con add type vlan con-name eth2.5 ifname eth2.5 dev eth2 id 5 ip4 10.10.10.6/24

- name: Create VID8 for testServer2
  shell: nmcli con add type vlan con-name eth3.8 ifname eth3.8 dev eth3 id 8 ip4 10.10.10.5/24

- name: Create VID8 for testClient2
  shell: nmcli con add type vlan con-name eth4.8 ifname eth4.8 dev eth4 id 8 ip4 10.10.10.6/24

- name: add files for routing
  file:
    path: "{{ item }}"
    state: touch
  with_items: "{{ route_files }}"

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/rule-eth1.5
    line: to 10.10.10.254 iif eth1.5 table 5

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/route-eth1.5
    line: 10.10.10.1 via 10.10.10.5 dev eth1.5 table 5

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/rule-eth2.5
    line: to 10.10.10.1 iif eth2.5 table 5

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/route-eth2.5
    line: 10.10.10.254 via 10.10.10.6 dev eth2.5 table 5

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/rule-eth3.8
    line: to 10.10.10.254 iif eth3.8 table 8

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/route-eth3.8
    line: 10.10.10.1 via 10.10.10.5 dev eth3.8 table 8

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/rule-eth4.8
    line: to 10.10.10.1 iif eth4.8 table 8

- name: input file
  lineinfile:
    dest: /etc/sysconfig/network-scripts/route-eth4.8
    line: 10.10.10.254 via 10.10.10.6 dev eth4.8 table 8

- name: start NetworkManager-dispatcher
  systemd:
    name: network
    state: restarted
    enabled: true

- name: Create bond
  shell: |
    nmcli con add type bond con-name bond0 ifname bond0 mode active-backup +bond.option fail_over_mac=1 ip4 10.10.15.2/24
    nmcli con add type bond-slave ifname eth5 master bond0
    nmcli con add type bond-slave ifname eth6 master bond0
    nmcli con up bond-slave-eth5
    nmcli con up bond-slave-eth6
    nmcli connection up bond0