- name: Create bond
  shell: |
    nmcli con add type bond con-name bond0 ifname bond0 mode active-backup +bond.option fail_over_mac=1 ip4 10.10.15.1/24
    nmcli con add type bond-slave ifname eth1 master bond0
    nmcli con add type bond-slave ifname eth2 master bond0
    nmcli con up bond-slave-eth1
    nmcli con up bond-slave-eth2
    nmcli connection up bond0
