---
- name: "##### DEFROUTE=no >> eth0 ######"
  shell: echo DEFROUTE=no >> {{ eth_00 }}
  notify: restart router

- name: "###### eth1 Server --> Router #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/eth1
    dest: "{{ eth_01 }}"
  notify: restart router
