---
- name: "##### eth1 inetRouter --> centralRouter #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/eth1
    dest: "{{ eth_01 }}"
  notify: restart router

- name: "##### route 192.168.0.0/16 #####"
  template:
    src: ../roles/templates/{{ inventory_hostname }}/route-eth1
    dest: "{{ route_eth1 }}"
  notify: restart router

- name: "##### set forwarding - true #####"
  sysctl:
    name: "{{ sysctl_name }}"
    value: "1"
    sysctl_set: yes
