- name: "deploy postgresql homework"
  hosts:
    - pg1
    - pg2
    - pg3
    - balancer
    - git1
    - git2
    - nginx1
    - nginx2
    - node1
    - node2
    - redis1
    - redis2
    - redis3

  gather_facts: false
  become: true
  roles:
    - role: roles
  tasks:
    - include: ../roles/tasks/network/network.yml
    - include: ../roles/tasks/{{ inventory_hostname }}.yml
  handlers:
    - include: ../roles/handlers/all_handlers.yml
