# -*- mode: ruby -*-
# vi: set ft=ruby:
Vagrant.configure("2") do |config|
	config.vm.define "zabbix" do |os|
		os.vm.box = "centos/7"
		os.vm.host_name = "zabbix"
		os.vm.network  "private_network", ip: '192.168.100.102'
		os.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "256"]
		end
        os.vm.provision "ansible" do |ansible|
		  #ansible.verbose = "vvv"
          ansible.playbook = "playbooks/zabbix.yml"
          ansible.become = "true"
        end
	end
end
