- name:
  command:
    - "rpm -i /vagrant/redis-6.0.6-1.el7.remi.x86_64.rpm"

- name: "Install Gitlab: Configuring firewall services"
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 6379/tcp
    - 6379/udp

- name:
  shell: |
    cat<<EOF>>/var/opt/gitlab/redis/redis.conf
    slaveof 192.168.100.151 6379
    masterauth TestPass
    requirepass TestPass
    EOF

- name: !!!
  systemd:
    name: gitlab
    state: restarted
    enabled: yes

- name: !!!
  shell: |
    cat<<EOF>>/etc/redis/redis-se
    sentinel monitor master01 192.168.100.111 6379 1
    sentinel down-after-milliseconds master01 3000
    sentinel failover-timeout master01 6000
    sentinel parallel-syncs master01 1
    bind 0.0.0.0
    sentinel auth-pass master01 P@ssw0rd
    EOF

- name: !!
  replace:
  regexp: deamonize on

- name: !!
  command: redis-serever /etc/redis/se --sen
