# -*- mode: ruby -*-
# vi: set ft=ruby:
home = ENV['HOME']

MACHINES = {
  :'inetRouter' => {
      :box_name => "centos/7",
  },
  :'centralRouter' => {
      :box_name => "centos/7",
  },
  :'testClient1' => {
      :box_name => "centos/7",
  },
  :'testServer1' => {
    :box_name => "centos/7",
  },
  :'testClient2' => {
      :box_name => "centos/7",
  },
  :'testServer2' => {
    :box_name => "centos/7",
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "128"]
            vb.name = boxname.to_s
            case boxname.to_s
            when "inetRouter"
              vb.customize ["modifyvm", :id, "--nic2", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet2", "bond"]
              vb.customize ["modifyvm", :id, "--nic3", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet3", "bond"]
            when "centralRouter"
              vb.customize ["modifyvm", :id, "--nic2", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet2", "testServer1"]
              vb.customize ["modifyvm", :id, "--nic3", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet3", "testClient1"]
              vb.customize ["modifyvm", :id, "--nic4", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet4", "testServer2"]
              vb.customize ["modifyvm", :id, "--nic5", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet5", "testClient2"]
              vb.customize ["modifyvm", :id, "--nic6", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet6", "bond"]
              vb.customize ["modifyvm", :id, "--nic7", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet7", "bond"]
            when "testServer1"
              vb.customize ["modifyvm", :id, "--nic2", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet2", "testServer1"]
            when "testClient1"
              vb.customize ["modifyvm", :id, "--nic2", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet2", "testClient1"]
            when "testServer2"
              vb.customize ["modifyvm", :id, "--nic2", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet2", "testServer2"]
            when "testClient2"
              vb.customize ["modifyvm", :id, "--nic2", "intnet"]
              vb.customize ["modifyvm", :id, "--intnet2", "testClient2"]
            end
	        end
          box.vm.provision "ansible" do |ansible|
            #ansible.verbose = "vv"
            ansible.playbook = "playbooks/vlan.yml"
            ansible.become = "true"
          end
        end
    end
end
