- name: "Install DRBD cluster: Create and Start Cluster"
  command: "{{ item }}"
  with_items:
    - "pcs cluster auth -u hacluster -p hacluster --force drbd-1 drbd-2"
    - "pcs cluster setup --name drbdcluster drbd-1 drbd-2"
    - "pcs cluster enable --all"
    - "pcs cluster start --all"
    - "pcs property set no-quorum-policy=ignore"
    - "pcs property set stonith-enabled=false"
    - 'pcs property set default-resource-stickiness="INFINITY"'

- name: "Install DRBD Cluster: create resourse IP"
  command: "{{ item }}"
  with_items:
    - "pcs resource create drdblusterIP ocf:heartbeat:IPaddr2 ip=192.168.100.230 nic=eth1 cidr_netmask=24 op monitor interval=5s timeout=15s"

- name: "Install DRBD Cluster: create resourse DrbdData"
  command: "{{ item }}"
  with_items:
    - "pcs cluster cib drbd_cfg"
    - "pcs -f drbd_cfg resource create DrbdData ocf:linbit:drbd drbd_resource=testdata1 op monitor interval=60s"
    - "pcs -f drbd_cfg resource master DrbdDataClone DrbdData master-max=1 master-node-max=1 clone-max=2 clone-node-max=1 notify=true"
    - "pcs cluster cib-push drbd_cfg"

- name: "Install DRBD Cluster: create resourse DrbdFS"
  command: "{{ item }}"
  with_items:
    - "pcs cluster cib fs_cfg"
    - 'pcs -f fs_cfg resource create DrbdFS ocf:heartbeat:Filesystem device="/dev/drbd0" directory="/mnt" fstype="xfs"'
    - "pcs -f fs_cfg constraint colocation add DrbdFS with DrbdDataClone INFINITY with-rsc-role=Master"
    - "pcs -f fs_cfg constraint order promote DrbdDataClone then start DrbdFS"
    - "pcs cluster cib-push fs_cfg"

- name: "Install DRBD Cluster: set op defaults"
  command: "{{ item }}"
  with_items:
    - "pcs resource op defaults timeout=210s"
