- name: "Create cluster Gitcluster: create cluster"
  command: "{{ item }}"
  with_items:
    - "systemctl restart postgresql-11.service"
    - 'sshpass -p "vagrant" ssh root@192.168.100.101 "systemctl restart postgresql-11.service"'

    - "pcs cluster auth -u hacluster -p hacluster --force node-1 node-2"
    - "pcs cluster setup --name pgcluster node-1 node-2"
    - "pcs cluster enable --all"
    - "pcs cluster start --all"
    - "pcs property set no-quorum-policy=ignore"
    - "pcs property set stonith-enabled=false"
    - "pcs resource create PGClusterIP ocf:heartbeat:IPaddr2 ip=192.168.100.200 nic=eth1 cidr_netmask=24 op monitor interval=3s timeout=15s"
    - 'pcs resource create PGSQLD ocf:heartbeat:pgsqlms bindir=/usr/pgsql-11/bin/ pgdata=/var/lib/pgsql/11/data op start timeout=60s op stop timeout=60s op promote timeout=30s op demote timeout=120s op monitor interval=15s timeout=10s role="Master" op monitor interval=16s timeout=10s role="Slave" op notify timeout=60s'
    - "pcs resource master PGSQL-HA PGSQLD notify=true"
    - "pcs constraint colocation add PGClusterIP with master PGSQL-HA INFINITY"
    - "pcs constraint order promote PGSQL-HA then start PGClusterIP symmetrical=false kind=Mandatory"
    - "pcs resource refresh"
#meta notify=true
#pcs resource create PGSQLD ocf:heartbeat:pgsqlms bindir=/usr/pgsql-11/bin/ pgdata=/var/lib/pgsql/11/data op start timeout=60s op stop timeout=60s op promote timeout=30s op demote timeout=120s op monitor interval=15s timeout=10s role="Master" op monitor interval=16s timeout=10s role="Slave" op notify timeout=60s
#pcs resource master PGSQL-HA PGSQLD notify=true
#pcs resource master PGSQL-HA PGSQLD master-max=1 master-min=1 master-node-max=1 clone-max=2 clone-node-max=1 notify=true
#
#pcs resource create PGSQLD ocf:heartbeat:pgsqlms bindir=/usr/pgsql-11/bin/ pgdata=/var/lib/pgsql/11/data op start timeout=5s op stop timeout=5s op promote timeout=3s op demote timeout=30s op monitor interval=9s timeout=5s role="Master" op monitor interval=9s timeout=5s role="Slave" op notify timeout=5s meta notify=true
#pcs resource master PGSQL-HA PGSQLD  master-max=1 master-node-max=1 clone-max=2 clone-node-max=1 notify=true
