- name: "Create cluster PROXY: create cluster"
  command: "{{ item }}"
  with_items:
    - "pcs cluster auth -u hacluster -p hacluster --force nginx-1 nginx-2"
    - "pcs cluster setup --name proxycluster nginx-1 nginx-2"
    - "pcs cluster enable --all"
    - "pcs cluster start --all"
    - "pcs property set no-quorum-policy=ignore"
    - "pcs property set stonith-enabled=false"
    - "pcs resource create ProxyCluster ocf:heartbeat:IPaddr2 ip=192.168.100.220 nic=eth1 cidr_netmask=24 op monitor interval=3s timeout=15s"
    - 'pcs resource create NginxCluster ocf:heartbeat:nginx configfile=/etc/nginx/nginx.conf op monitor timeout="5s" interval="5s"'
    - "pcs constraint colocation add NginxCluster ProxyCluster INFINITY"
    - "pcs constraint order ProxyCluster then NginxCluster"
