- name: "deploy homework"
  hosts:
    - zabbix
  gather_facts: false
  become: true
  tasks:
    - name:
      shell: |
        rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        yum install centos-release-scl -y
        sed -i 's!enabled=0!enabled=1!' /etc/yum.repos.d/zabbix.repo
        yum clean all
        yum install zabbix-server-pgsql zabbix-agent -y
        yum install zabbix-web-pgsql-scl zabbix-nginx-conf-scl -y
        yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm -y
        yum install postgresql11-server -y
        /usr/pgsql-11/bin/postgresql-11-setup initdb
        sed -i 's/\#\ DBPassword=/DBPassword=12345678/' /etc/zabbix/zabbix_server.conf
        sed -i 's!#        listen!listen!' /etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf
        sed -i 's!#        server_name!server_name!' /etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf
        sed -i 's!listen.acl_users = apache!listen.acl_users = apache,nginx!'  /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
        sed -i  's!; php_value\[date.timezone]!php_value\[date.timezone]!' /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
        sed -i 's!listen       80 default_server;!listen       80;!' /etc/opt/rh/rh-nginx116/nginx/nginx.conf
        sed -i 's!listen       [::]:80 default_server;!listen       [::]:80;!' /etc/opt/rh/rh-nginx116/nginx/nginx.conf
        sed -i 's!# DBPort=!DBPort=5432!' /etc/zabbix/zabbix_server.conf
        sudo setsebool -P httpd_can_network_connect 1
        sed -i 's!host    all             all             ::1/128                 ident!host    all             all             ::1/128                 trust!' /var/lib/pgsql/11/data/pg_hba.conf
        sed -i 's!host    all             all             127.0.0.1/32            ident!host    all             all             127.0.0.1/32            trust!' /var/lib/pgsql/11/data/pg_hba.conf
        sed -i 's!local   all             all                                     peer!local   all             all                                     trust!' /var/lib/pgsql/11/data/pg_hba.conf
        systemctl restart zabbix-server zabbix-agent rh-nginx116-nginx rh-php72-php-fpm postgresql-11.service
        systemctl enable zabbix-server zabbix-agent rh-nginx116-nginx rh-php72-php-fpm postgresql-11.service

#sudo -u postgres createuser --pwprompt zabbix
#sudo -u postgres createdb -O zabbix zabbix
#zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix

#zabbix_login: Admin/zabbix
#zabbix DBPassword: 12345678
#zabbix DBPort: 5432
