- name: Start nfs.servise
  systemd:
    name: nfs-server.service
    state: started
    enabled: yes

- name: Create /obmen
  file:
    path: /obmen
    state: directory
    mode: "0777"

- name: Settings /etc/exports
  shell: |
    echo "/obmen 192.168.100.102(rw)" >> /etc/exports
    exportfs -r

- name: Start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Rules for firewalld
  shell: |
    firewall-cmd \
    --add-port=50370/udp \
    --add-port=52169/udp \
    --add-port=20048/udp \
    --add-port=2049/udp \
    --add-port=42494/udp \
    --add-port=41310/udp \
    --permanent
    firewall-cmd --permanent --add-service=nfs
    firewall-cmd --permanent --add-service=mountd
    firewall-cmd --permanent --add-service=rpc-bind
    firewall-cmd --reload
