- name: "deploy homework dynamic_web"
  hosts:
    - web
  gather_facts: false
  become: true
  roles:
    - role: roles
  tasks:
    - include: ../roles/tasks/gitlab_install.yml
    - include: ../roles/tasks/elk_install.yml
    - include: ../roles/tasks/zabbix_install.yml
#  handlers:
#    - include: ../roles/handlers/all_handlers.yml
