---
- name: "Create file for NGINX repo"
  file:
    path: "{{ nginx_repo_path }}"
    state: touch

- name: "Add official NGINX repo"
  blockinfile:
    path: "{{ nginx_repo_path }}"
    block: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_notfixes=true

- name: Install NGINX
  yum:
    name: nginx
    state: present
  notify:
    - start nginx

- name: "Copy index.html"
  template:
    src: roles/nginx/templates/index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: "Copy default.conf"
  template:
    src: roles/nginx/templates/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - reload nginx
## Более оптимальный метод перечитать nginx
#- name: "Reload nginx"
#      shell: "nginx -t && nginx -s reload"

## проверка работы nginx с новыми параметрами, в случае кода возврата отличного от 200, playbook прерывается
#- name: "Check that web-site working properly"
#  uri:
#    url: http://localhost:{{ nginx_port }}
#    return_content: true
#  register: website
#  failed_when: website.status !=200
