# -*- mode: ruby -*-
# vi: set ft=ruby:
home = ENV['HOME']

MACHINES = {
  :'centralServer' => {
    :box_name => "centos/7",
  },
	:'inetRouter' => {
      :box_name => "centos/7",
  },
  :'inetRouter2' => {
      :box_name => "centos/7",
  },
	:'centralRouter' => {
      :box_name => "centos/7",
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "128"]
            vb.name = boxname.to_s
            case boxname.to_s
	    when "centralServer"
            vb.customize ["modifyvm", :id, "--nic2", "intnet"]
	    vb.customize ["modifyvm", :id, "--intnet2", "srv-subnet"]
            when "inetRouter"
            vb.customize ["modifyvm", :id, "--nic2", "intnet"]
	    vb.customize ["modifyvm", :id, "--intnet2", "central_inet_line"]
	    when "inetRouter2"
	    vb.customize ["modifyvm", :id, "--nic2", "intnet"]
	    vb.customize ["modifyvm", :id, "--intnet2", "nginx_line"]
            vb.customize ["modifyvm", :id, "--nic3", "hostonly"]
            vb.customize ["modifyvm", :id, "--hostonlyadapter3", "vboxnet0"]
            when "centralRouter"
            vb.customize ["modifyvm", :id, "--nic2", "intnet"]
	    vb.customize ["modifyvm", :id, "--intnet2", "central_inet_line"]
	    vb.customize ["modifyvm", :id, "--nic3", "intnet"]
	    vb.customize ["modifyvm", :id, "--intnet3", "nginx_line"]
            vb.customize ["modifyvm", :id, "--nic6", "intnet"]
            vb.customize ["modifyvm", :id, "--intnet6", "srv-subnet"]
            end
	   end
          box.vm.provision "ansible" do |ansible|
            #ansible.verbose = "vv"
            #ansible.playbook = "provision/playbook.yml"
            ansible.playbook = "playbooks/iptab.yml"
            ansible.become = "true"
          end
        end
    end
end
