# -*- mode: ruby -*-
# vi: set ft=ruby:
Vagrant.configure("2") do |config|
	config.vm.define "git" do |os|
		os.vm.box = "centos/7"
		os.vm.host_name = "nginx.example.com"
		os.vm.network  "private_network", ip: '192.168.100.112'
		os.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "512"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]

		end
		os.vm.provision "shell", inline: <<SHELL
SHELL
	end
## Устанавливаем связь между каталогом "./src" хост-системы
## и каталогом "/home/vagrant" гостевой системы.
#		config.vm.synced_folder "./src", "/home/vagrant"
end

