# -*- mode: ruby -*-
# vi: set ft=ruby:
Vagrant.configure("2") do |config|
	config.vm.define "web" do |web|
		web.vm.box = "centos/7"
		web.vm.host_name = "web"
		web.vm.network  "private_network", ip: '192.168.100.111'
		web.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "4096"]
			vb.customize ["modifyvm", :id, "--cpus", "2"]

		end
		web.vm.provision "ansible" do |ansible|
			ansible.playbook = "playbooks/dynamic_web.yml"
			ansible.become = "true"
			#ansible.verb = "vvv"
		end
	end
end
